"""Curated MiniMax H3 music directions for the web studio and API."""
from __future__ import annotations


def _p(name: str, category: str, style: str, instrumentation: str,
       vocalist: str = "a natural, expressive professional singer with clear diction") -> dict[str, str]:
    return {
        "name": name,
        "category": category,
        "style": style,
        "instrumentation": instrumentation,
        "vocalist": vocalist,
    }


MUSIC_PRESETS = {
    # Pop
    "pop_radio": _p("Modern radio pop", "Pop", "Polished contemporary pop at 112 BPM with tight verses, a rising pre-chorus, and a huge concise chorus.", "Punchy acoustic-electronic drums, warm synth bass, palm-muted guitar, bright keys, stacked hook harmonies, and a clean final lift.", "a charismatic young adult pop singer with natural phrasing, crisp diction, and an emotionally open chorus"),
    "pop_dance": _p("Glossy dance-pop", "Pop", "Upbeat glossy dance-pop at 122 BPM, bright and confident, with a propulsive chorus and clean club-ready structure.", "Four-on-the-floor kick, tight claps, plucky synth bass, shimmering arpeggios, wide pads, and layered chorus vocals.", "a confident female pop vocalist with bright tone, playful rhythmic phrasing, and polished harmonies"),
    "pop_bubblegum": _p("Bubblegum pop", "Pop", "Effervescent bubblegum pop at 128 BPM with sugary hooks, quick transitions, and an irresistibly simple chorus.", "Bouncy drums, handclaps, rubbery bass, sparkling bells, bright rhythm guitar, and colorful synth stabs.", "a bubbly youthful adult singer with a vivid smile in the voice, clean enunciation, and energetic ad-libs"),
    "pop_power": _p("Power pop", "Pop", "Driving power pop at 148 BPM with compact verses, ringing hooks, and a triumphant sing-along chorus.", "Crunchy doubled guitars, melodic bass, live punchy drums, tambourine, and selective vocal doubles.", "an energetic adult singer with a clear melodic belt, conversational verses, and a big unforced chorus"),
    "pop_indie": _p("Indie pop", "Pop", "Warm offbeat indie pop at 104 BPM with human timing, bittersweet melody, and an understated hook that grows naturally.", "Dry drums, melodic picked bass, chorus guitar, compact analog synth, hand percussion, and intimate backing vocals.", "an intimate slightly imperfect singer with distinctive character, relaxed diction, and emotionally specific phrasing"),
    "pop_dark": _p("Dark pop", "Pop", "Nocturnal dark pop at 96 BPM with spacious verses, sub-heavy tension, and a restrained but memorable chorus.", "Deep sub bass, clipped electronic drums, detuned piano, glassy synth textures, breathy doubles, and sudden negative space.", "a low, close-miked female vocalist with controlled intensity, natural breath, precise words, and a dangerous calm"),
    "pop_synth": _p("Synth-pop anthem", "Pop", "Melodic synth-pop at 118 BPM with an immediate motif, expansive chorus, and polished dramatic arc.", "Analog bass sequence, gated snare, pulsing eighth-note synths, luminous pads, lead hook, and stacked vocal harmonies.", "a polished adult pop singer with warm midrange, clear sustained notes, and emotionally escalating choruses"),
    "pop_disco": _p("Disco pop", "Pop", "Modern disco-pop at 118 BPM with elastic groove, glamorous chord changes, and a chorus built for movement.", "Four-on-the-floor drums, octave bass, muted funk guitar, string flourishes, electric piano, handclaps, and glossy vocals.", "a stylish soulful singer with agile rhythm, warm chest voice, clear lyrics, and playful falsetto accents"),
    "pop_bedroom": _p("Bedroom pop", "Pop", "Close, homemade bedroom pop at 86 BPM with vulnerable verses and a softly addictive refrain.", "Muted drum machine, warm electric piano, gently detuned guitar, soft mono synth bass, room noise, and sparse doubles.", "a very close natural young adult voice with conversational timing, quiet emotion, audible breath, and no theatrical projection"),
    "pop_hyper": _p("Hyperpop rush", "Pop", "Hyper-detailed hyperpop at 158 BPM with abrupt dynamic edits, explosive hooks, and a coherent melodic center.", "Distorted kick, metallic claps, supersaw bursts, pitch-bent bass, glittering digital leads, vocal chops, and hard stop transitions.", "an animated high-energy adult singer with sharp diction, elastic melodic phrasing, and controlled processed vocal layers"),

    # K-pop
    "kpop_glossy": _p("K-pop glossy", "K-pop", "Precision K-pop at 124 BPM with a sleek verse, tension-building pre-chorus, explosive hook, and polished dance-break energy.", "Tight hybrid drums, sub bass, glossy synth plucks, rhythmic guitar, bright brass accents, layered group chants, and cinematic risers.", "a polished female K-pop lead with crisp English diction, agile phrasing, bright tone, and tightly stacked hook harmonies"),
    "kpop_girl_crush": _p("K-pop girl crush", "K-pop", "Bold girl-crush K-pop at 106 BPM with swaggering half-time verses, a dramatic build, and a commanding chant hook.", "Heavy 808s, martial snares, distorted synth brass, sparse plucks, stomps, vocal stacks, and a sharp dance breakdown.", "a confident female pop-rap lead alternating cool low-register lines with a strong melodic chorus and precise group responses"),
    "kpop_dreamy": _p("Dreamy K-pop", "K-pop", "Dreamy K-pop at 110 BPM with floating verses, luminous harmony, and a graceful euphoric chorus.", "Soft breakbeat drums, round bass, crystalline bells, chorus guitar, airy pads, orchestral sparkles, and close harmony stacks.", "a gentle clear female lead with airy but intelligible tone, delicate emotion, and smooth layered harmonies"),
    "kpop_boy_group": _p("K-pop boy-group", "K-pop", "Athletic boy-group K-pop at 126 BPM with rhythmic verses, a soaring pre-chorus, and a broad anthemic hook.", "Punchy dance drums, syncopated bass, percussive synths, distorted guitar accents, brass hits, and group-response vocals.", "a versatile male pop lead with clean youthful tone, rhythmic precision, controlled high notes, and unified group chants"),
    "kpop_retro": _p("Retro K-pop", "K-pop", "Retro city-pop-influenced K-pop at 116 BPM with sophisticated chords, buoyant groove, and a silky melodic chorus.", "Slap bass, Linn-style drums, electric piano, clean chorus guitar, analog brass, sax accents, and glossy vocal stacks.", "a warm sophisticated female vocalist with relaxed groove, bright upper register, and smooth professional harmonies"),
    "kpop_rnb": _p("K-R&B after dark", "K-pop", "Sleek Korean-inspired contemporary R&B at 82 BPM with syncopated pocket, spacious sensual verses, and a refined chorus.", "Deep kick, finger snaps, elastic sub bass, Rhodes chords, muted guitar, granular ambience, and restrained harmonies.", "a close-miked adult singer with silky low-mid tone, fluent rhythmic phrasing, natural breaths, and intimate clear diction"),

    # Rock
    "rock_hard": _p("Modern hard rock", "Rock", "Muscular modern hard rock at 132 BPM with tense verses, a climbing pre-chorus, and a massive melodic chorus.", "Drop-tuned doubled guitars, driving live drums, gritty bass, restrained synth support, feedback transitions, and gang accents.", "a powerful adult rock singer with believable grit, clear words, dynamic control, and a melodic arena-sized chorus"),
    "rock_arena": _p("Arena rock anthem", "Rock", "Expansive arena rock at 126 BPM with steady build, heroic guitar hooks, and a wide audience-ready chorus.", "Huge live drums, open power chords, melodic bass, sustained lead guitar, piano support, handclaps, and broad backing vocals.", "a commanding rock vocalist with warm rasp, strong pitch, intelligible lyrics, and a soaring but human chorus"),
    "rock_classic": _p("Classic hard rock", "Rock", "Seventies-inspired hard rock at 118 BPM with loose swagger, blues-rooted riffs, and a memorable vocal refrain.", "Cranked tube-amp guitars, live room drums, growling bass, Hammond organ, tambourine, and expressive lead guitar fills.", "a seasoned rock singer with smoky grit, loose confident pocket, strong melodic identity, and natural live-room phrasing"),
    "rock_garage": _p("Garage rock", "Rock", "Raw garage rock at 156 BPM, immediate and scrappy, with short verses and a shouted melodic hook.", "Overdriven mono guitars, distorted bass, dry crashing drums, handclaps, cheap organ, and minimal overdubs.", "an urgent charismatic singer with rough edges, clear core melody, spontaneous shouts, and believable live energy"),
    "rock_alt": _p("Alternative rock", "Rock", "Dynamic alternative rock at 112 BPM with restrained verses, textural tension, and a cathartic full-band chorus.", "Layered clean and distorted guitars, weighty bass, roomy drums, atmospheric noise, and a melodic counterline.", "an emotionally grounded adult vocalist moving from intimate speechlike verses to a resonant controlled chorus"),
    "rock_grunge": _p("Grunge", "Rock", "Heavy grunge at 102 BPM with sludgy quiet-loud dynamics, unresolved tension, and a raw hook.", "Fuzzed guitars, thick pick bass, loose hard-hitting drums, feedback, and sparse doubled vocals.", "a weathered low rock voice with aching grit, understandable lyrics, imperfect human timing, and explosive choruses"),
    "rock_pop_punk": _p("Pop-punk", "Rock", "Fast melodic pop-punk at 172 BPM with tight verse momentum, stop-start transitions, and a huge youthful chorus.", "Palm-muted guitars, bright power chords, driving pick bass, crisp acoustic drums, octave leads, and gang vocals.", "an energetic youthful adult singer with nasal edge, fast clean diction, emotional urgency, and catchy stacked hooks"),
    "rock_post_punk": _p("Post-punk night drive", "Rock", "Lean nocturnal post-punk at 136 BPM with hypnotic repetition, detached verses, and a widening refrain.", "Angular chorus guitar, melodic picked bass, dry motorik drums, icy mono synth, and controlled feedback.", "a cool low adult voice with restrained emotion, precise rhythmic diction, and a subtly haunted melodic refrain"),
    "rock_psych": _p("Psychedelic rock", "Rock", "Slow-burning psychedelic rock at 92 BPM with circular harmony, evolving textures, and a hallucinatory guitar climax.", "Fuzz guitar, rotating organ, roomy drums, melodic bass, tape echoes, reverse textures, and a long expressive solo.", "a dreamy characterful singer with relaxed diction, sustained phrases, subtle doubles, and vintage room ambience"),
    "rock_southern": _p("Southern rock", "Rock", "Rolling southern rock at 116 BPM with bluesy storytelling verses, a lifting chorus, and a twin-guitar payoff.", "Crunchy rhythm guitars, slide guitar, piano, warm bass, live shuffle-leaning drums, and twin lead harmony.", "a warm seasoned singer with light regional color, storytelling clarity, soulful grit, and an easy full-voice chorus"),
    "rock_emo": _p("Emo rock", "Rock", "Emotionally escalating emo rock at 148 BPM with confessional verses, suspended pre-chorus tension, and a cathartic hook.", "Octave guitar figures, palm-muted verses, explosive open chords, melodic bass, urgent drums, and selective gang vocals.", "an expressive youthful adult vocalist with vulnerable close verses, clear lyrics, and a strained but controlled chorus"),
    "rock_math": _p("Math-rock shimmer", "Rock", "Intricate melodic math rock at 124 BPM with shifting accents, clean interlocking patterns, and a concise emotional refrain.", "Tapped clean guitars, articulate bass, syncopated live drums, chiming harmonics, and restrained ambient swells.", "a light natural singer with conversational phrasing, careful placement across odd accents, and an unforced memorable hook"),

    # Metal
    "metal_heavy": _p("Traditional heavy metal", "Metal", "Driving traditional heavy metal at 150 BPM with galloping verses, dramatic pre-chorus, and a triumphant melodic refrain.", "Twin distorted guitars, galloping bass, thunderous acoustic drums, harmonized leads, and a concise guitar solo.", "a powerful clean metal singer with dramatic projection, crisp words, controlled vibrato, and strong sustained high notes"),
    "metal_metalcore": _p("Modern metalcore", "Metal", "Modern metalcore at 142 BPM with tense syncopated verses, a punishing breakdown, and a melodic wide-screen chorus.", "Low-tuned guitars, precise double kick, aggressive bass, electronic impacts, ambient clean guitars, and layered chorus vocals.", "an adult vocalist alternating intelligible harsh rhythm vocals with a strong clean melodic chorus"),
    "metal_doom": _p("Doom metal", "Metal", "Monolithic doom metal at 62 BPM with enormous space, descending riffs, and patient ritual-like development.", "Down-tuned sustained guitars, massive slow drums, distorted bass, low organ drone, feedback, and sparse lead lament.", "a deep resonant singer with slow deliberate diction, grave melodic phrases, and long natural room decay"),
    "metal_industrial": _p("Industrial metal", "Metal", "Mechanical industrial metal at 128 BPM with rigid pulse, grinding verse rhythm, and a severe hook.", "Programmed kick-snare machinery, distorted guitars, sequenced bass, metallic impacts, noise gates, and synthetic choir texture without words.", "a forceful low adult vocalist with clipped precise diction, controlled distortion, and a cold commanding refrain"),
    "metal_power": _p("Power metal", "Metal", "Fast uplifting power metal at 172 BPM with galloping momentum, dramatic key changes, and a soaring victorious chorus.", "Twin lead guitars, rapid double kick, bright bass, orchestral support, choir-like wordless pads, and virtuosic solo.", "a clear heroic singer with excellent diction, resonant high register, theatrical energy, and disciplined sustained notes"),
    "metal_prog": _p("Progressive metal", "Metal", "Progressive metal at 118 BPM with shifting meter, tightly recurring motifs, atmospheric space, and a controlled heavy climax.", "Extended-range guitars, articulate bass, detailed acoustic drums, evolving synth pads, piano interlude, and motif-based lead work.", "a versatile adult singer with intimate clean verses, precise rhythmic placement, clear consonants, and a powerful measured peak"),
    "metal_blackgaze": _p("Atmospheric blackgaze", "Metal", "Atmospheric blackgaze at 154 BPM with tremolo-driven ascent, enormous reverb, and a luminous wall-of-sound climax.", "Tremolo guitars, blasting then half-time drums, sustained bass, distant pads, feedback bloom, and layered texture.", "a distant emotionally raw adult vocalist embedded in the mix, with intelligible central phrases and an ethereal clean refrain"),

    # Hip-hop and rap
    "rap_boom_bap": _p("Boom-bap rap", "Hip-hop / Rap", "Head-nodding boom-bap at 88 BPM with dusty swing, clear four-bar phrases, and space for dense storytelling.", "Chopped soul-like harmonic fragments, hard dry kick and snare, warm bass, vinyl texture, sparse horn punctuation, and turntable accents.", "a confident adult rapper with natural conversational authority, excellent diction, internal-rhyme precision, and no sing-song delivery"),
    "rap_trap": _p("Modern trap", "Hip-hop / Rap", "Dark modern trap at 142 BPM half-time with spacious verses, memorable cadence changes, and a sharp melodic hook.", "Deep sliding 808, crisp snare, rapid hi-hat variations, ominous bell motif, filtered pad, and selective vocal doubles.", "a charismatic adult rapper with precise pocket, clean words, controlled intensity, and a melodic but intelligible hook"),
    "rap_drill": _p("Drill", "Hip-hop / Rap", "Tense drill at 142 BPM with sliding bass countermotion, clipped rhythmic space, and relentless forward pressure.", "Gliding 808s, syncopated kick, hard snare, skittering hats, cold minor-key piano, and sparse orchestral stabs.", "a focused low-register rapper with crisp consonants, disciplined breath, varied cadence, and restrained menace"),
    "rap_west": _p("West Coast cruise", "Hip-hop / Rap", "Laid-back West Coast rap at 94 BPM with elastic funk pocket, sunlit chord movement, and an easy rolling hook.", "Round synth bass, dry drums, high synth whistle, electric piano, muted guitar, handclaps, and talkbox-like wordless accents.", "a relaxed charismatic rapper with clear storytelling diction, behind-the-beat confidence, and a smooth memorable refrain"),
    "rap_cloud": _p("Cloud rap", "Hip-hop / Rap", "Weightless cloud rap at 132 BPM half-time with hazy harmony, floating cadence, and a dreamy repeated hook.", "Soft 808, diffused hats, washed synth pad, reversed bells, distant choir texture without words, and long delays.", "an airy intimate rapper with fluid melodic cadence, understandable lyrics, soft doubles, and emotionally detached calm"),
    "rap_rage": _p("Rage rap", "Hip-hop / Rap", "High-energy rage rap at 154 BPM with distorted color, abrupt drops, and a frantic chant-ready hook.", "Overdriven 808, bright supersaw lead, clipped kicks, rapid hats, digital effects, and explosive transitions.", "an animated adult rapper with sharp rhythmic attack, clear core words, aggressive ad-libs, and a catchy shouted hook"),
    "rap_jazz": _p("Jazz rap", "Hip-hop / Rap", "Sophisticated jazz rap at 90 BPM with loose swing, evolving chords, and understated chorus movement.", "Upright bass, brushed breakbeat, Rhodes, muted trumpet phrases, vibraphone accents, and subtle vinyl texture.", "an articulate adult rapper with warm conversational tone, detailed storytelling, relaxed pocket, and precise intelligibility"),
    "rap_emo": _p("Emo rap", "Hip-hop / Rap", "Melodic emo rap at 132 BPM half-time with exposed verses, aching guitar loop, and a direct confessional hook.", "Clean picked guitar, sub bass, sparse trap drums, ambient pad, reverse swells, and restrained vocal doubles.", "a vulnerable youthful adult vocalist blending melodic rap and sung phrases with clear words, natural cracks, and intimate emotion"),
    "rap_lofi": _p("Lo-fi freestyle", "Hip-hop / Rap", "Warm lo-fi hip-hop at 78 BPM with lazy swing, compact loop evolution, and ample room for relaxed bars.", "Dusty drums, muted jazz-piano chords, soft electric bass, vinyl crackle, and occasional sax fragments.", "a close conversational rapper with easy timing, warm tone, crisp enough diction, and understated personality"),
    "rap_alt": _p("Alternative hip-hop", "Hip-hop / Rap", "Inventive alternative hip-hop at 104 BPM with unexpected textures, section-level beat changes, and a left-field hook.", "Broken drums, distorted acoustic samples, rubbery bass, prepared piano, odd percussion, and abrupt negative space.", "a distinctive characterful rapper with agile cadence, theatrical detail, excellent diction, and a boldly melodic refrain"),

    # R&B, soul and funk
    "rnb_modern": _p("Modern R&B", "R&B / Soul", "Polished contemporary R&B at 76 BPM with spacious pocket, intimate verses, and a smoothly widening chorus.", "Deep sub bass, soft kick, finger snaps, Rhodes extensions, muted guitar, atmospheric synths, and restrained harmonies.", "a close-miked soulful singer with natural runs, warm low-mid tone, excellent diction, and emotionally detailed phrasing"),
    "rnb_neosoul": _p("Neo-soul", "R&B / Soul", "Organic neo-soul at 84 BPM with behind-the-beat groove, rich chord substitutions, and a human live-room feel.", "Rhodes, round electric bass, dry pocket drums, muted guitar, organ touches, and responsive backing harmonies.", "a deeply expressive adult soul singer with conversational phrasing, tasteful melisma, clear words, and relaxed rhythmic command"),
    "rnb_quiet_storm": _p("Quiet storm", "R&B / Soul", "Luxurious slow-jam R&B at 70 BPM with patient verses, romantic harmonic movement, and a velvety chorus.", "Electric piano, fretless bass, soft drum machine, clean chorus guitar, warm pads, saxophone fills, and silky harmonies.", "a sensual mature singer with smooth low register, unhurried natural phrasing, articulate lyrics, and controlled breath"),
    "soul_classic": _p("Classic soul", "R&B / Soul", "Sixties-inspired soul at 108 BPM with tight verse groove, call-and-response energy, and a joyful rising chorus.", "Live drums, melodic bass, tambourine, piano, organ, horn section, rhythm guitar, and responsive backing trio.", "a commanding soulful singer with warm grit, gospel-informed dynamics, precise words, and emotionally spontaneous ad-libs"),
    "soul_gospel": _p("Gospel soul", "R&B / Soul", "Uplifting gospel-soul at 96 BPM with a patient opening, call-and-response build, and a full communal final chorus.", "Piano, Hammond organ, live bass and drums, handclaps, restrained brass, and a layered response choir singing only supplied lyrics.", "a powerful adult lead with rich human tone, clear testimony-like delivery, controlled runs, and dynamic choir interaction"),
    "funk_70s": _p("Deep funk", "R&B / Soul", "Tight seventies funk at 106 BPM with interlocking syncopation, short vocal phrases, and a relentless pocket.", "Slap bass, dry drums, wah guitar, clavinet, horn stabs, hand percussion, and compact group responses.", "a charismatic rhythmic singer with sharp diction, playful spoken-sung phrasing, soulful grit, and disciplined call-and-response"),
    "funk_electro": _p("Electro-funk", "R&B / Soul", "Sleek electro-funk at 116 BPM with robotic-tight rhythm, elastic bass, and a glossy vocal hook.", "Punchy drum machine, analog synth bass, talkbox-like wordless texture, bright polysynth chords, claps, and clean rhythm guitar.", "a stylish soulful vocalist with crisp rhythmic phrasing, warm personality, clean hook stacks, and controlled falsetto"),

    # Electronic
    "electro_house": _p("Festival house", "Electronic", "Peak-time melodic house at 126 BPM with disciplined build, clean drop, and a memorable instrumental motif.", "Four-on-the-floor kick, offbeat bass, bright pluck, rising noise, wide supersaws, vocal-like synth hook, and sidechained pads."),
    "electro_deep_house": _p("Deep house", "Electronic", "Deep house at 122 BPM with restrained late-night groove, subtle harmonic evolution, and smooth transitions.", "Rounded kick, shuffled hats, warm sub bass, minor seventh chords, soft organ stab, filtered texture, and sparse percussion."),
    "electro_french": _p("Filter disco house", "Electronic", "Funky filter-house at 124 BPM with looping disco harmony, dramatic filter movement, and joyous compression-driven lift.", "Four-on-the-floor drums, chopped rhythm-guitar loop, elastic bass, filtered strings, handclaps, and bright synth accents."),
    "electro_techno": _p("Warehouse techno", "Electronic", "Hypnotic warehouse techno at 132 BPM with slow additive evolution, industrial space, and no conventional verse-chorus structure.", "Heavy kick, rolling low percussion, metallic hats, dark sequenced bass, resonant synth pulses, and distant machine noise."),
    "electro_trance": _p("Euphoric trance", "Electronic", "Euphoric trance at 138 BPM with long harmonic build, emotional breakdown, and a luminous final drop.", "Driving kick, offbeat bass, bright arpeggio, wide supersaws, gated pads, snare build, and soaring lead melody."),
    "electro_dnb": _p("Liquid drum & bass", "Electronic", "Liquid drum and bass at 174 BPM with flowing breakbeats, warm harmony, and a graceful melodic arc.", "Detailed chopped breaks, deep sub bass, Rhodes chords, airy pads, soft guitar fragments, and an expressive lead motif."),
    "electro_neuro": _p("Neuro drum & bass", "Electronic", "Aggressive neurofunk drum and bass at 174 BPM with precise edits, evolving bass design, and controlled high-impact drops.", "Tight breakbeats, resampled growl bass, sub reinforcement, metallic percussion, dark atmospheres, and glitch transitions."),
    "electro_dubstep": _p("Cinematic dubstep", "Electronic", "Cinematic dubstep at 145 BPM half-time with suspenseful opening, dramatic impact, and a rhythmically varied bass drop.", "Massive half-time drums, sub bass, modulated growls, orchestral braams, granular impacts, and a sparse melodic motif."),
    "electro_synthwave": _p("Neon synthwave", "Electronic", "Eighties-inspired synthwave at 108 BPM, nocturnal and cinematic, with a clear driving hook.", "Gated snare, analog arpeggiated bass, chorus-drenched pads, bright polysynth chords, and sustained lead melody."),
    "electro_ambient": _p("Deep ambient", "Electronic", "Slowly evolving beatless ambient music with continuous texture, patient harmonic change, and no sudden climax.", "Granular pads, low sine drone, bowed metallic overtones, distant piano harmonics, field-recording air, and long reverbs."),
    "electro_triphop": _p("Noir trip-hop", "Electronic", "Smoky trip-hop at 82 BPM with heavy swung break, cinematic tension, and spacious hypnotic repetition.", "Dusty breakbeat, deep bass, minor-key Rhodes, tremolo guitar, vinyl hiss, string fragments, and dub delays.", "a smoky low close-miked singer with unhurried diction, intimate restraint, and subtly haunted melodic lines"),
    "electro_futurebass": _p("Future bass", "Electronic", "Emotional future bass at 150 BPM half-time with delicate opening, pitched harmonic lift, and a broad colorful drop.", "Soft piano, crisp drums, sub bass, sidechained chord stacks, pitched vocal-like synth texture, glittering percussion, and wide pads."),

    # Jazz and blues
    "jazz_swing": _p("Small-combo swing", "Jazz / Blues", "A strutting small-combo swing at 132 BPM, played live in one room with conversational solos.", "Walking upright bass, brushed-to-stick drums, piano comping, muted trumpet, tenor sax, and short traded phrases.", "a warm classic jazz singer with relaxed behind-the-beat phrasing, crystal-clear lyrics, and tasteful melodic variation"),
    "jazz_noir": _p("Noir jazz club", "Jazz / Blues", "Slow nocturnal jazz ballad at 66 BPM with smoky harmonic tension, large spaces, and late-night club intimacy.", "Brushes, upright bass, dark piano voicings, breathy tenor sax, muted trumpet, and subtle room ambience.", "a mature low-voiced jazz singer with intimate microphone technique, deliberate diction, and emotionally restrained phrasing"),
    "jazz_bebop": _p("Bebop sprint", "Jazz / Blues", "Fast bebop at 224 BPM with agile harmonic movement, compact head, and virtuosic but coherent solo exchanges.", "Ride-led drums, walking bass, piano comping, alto sax, trumpet, and clean live-room separation."),
    "jazz_bossa": _p("Bossa jazz", "Jazz / Blues", "Intimate bossa nova jazz at 126 BPM with soft syncopation, elegant harmony, and effortless restraint.", "Nylon guitar, gentle cross-stick, upright bass, soft piano, flute accents, and very light shaker.", "a soft natural singer with close diction, subtle rhythmic placement, minimal vibrato, and warm conversational intimacy"),
    "blues_electric": _p("Electric blues club", "Jazz / Blues", "Slow electric blues at 72 BPM with deep shuffle pocket, expressive vocal space, and a burning final guitar answer.", "Tube-amp guitar, Hammond organ, live bass, shuffle drums, piano, and responsive lead-guitar fills.", "a seasoned blues singer with lived-in grit, clear storytelling, flexible timing, and emotionally responsive phrasing"),
    "blues_delta": _p("Delta blues", "Jazz / Blues", "Raw acoustic Delta blues at 82 BPM with irregular human pulse, stark storytelling, and call-and-response guitar.", "One resonant steel-string guitar, bottleneck slide, foot stomp, hand tap, and close wooden-room ambience.", "a weathered intimate singer with natural regional color, direct diction, free timing, and unpolished emotional truth"),
    "jazz_fusion": _p("Jazz fusion", "Jazz / Blues", "Electric jazz fusion at 118 BPM with odd-meter accents, fluid harmony, and a technically sharp ensemble peak.", "Fretless bass, electric piano, syncopated drums, clean electric guitar, analog lead synth, and tightly arranged unison lines."),
    "jazz_lounge": _p("Velvet lounge", "Jazz / Blues", "Sophisticated lounge jazz at 92 BPM with easy swing, polished harmony, and intimate cocktail-room scale.", "Upright bass, brushes, piano, vibraphone, soft flute, muted guitar, and subtle room tone.", "an elegant adult singer with smooth natural tone, articulate lyrics, gentle swing, and understated charm"),

    # Country and folk
    "country_modern": _p("Modern country", "Country / Folk", "Contemporary country at 104 BPM with vivid narrative verses, a rising pre-chorus, and a broad heartfelt hook.", "Acoustic guitar, live drums, electric bass, clean electric guitar, pedal steel, mandolin touches, and supportive harmonies.", "a natural adult country singer with warm conversational storytelling, clear lyrics, light regional color, and a full emotional chorus"),
    "country_outlaw": _p("Outlaw country", "Country / Folk", "Dusty outlaw country at 92 BPM with laconic storytelling, steady train-like groove, and a weathered refrain.", "Dry acoustic guitar, Telecaster twang, upright-like bass, restrained drums, pedal steel, and harmonica accents.", "a seasoned low country voice with dry humor, relaxed timing, intelligible words, and no glossy pop affectation"),
    "country_honkytonk": _p("Honky-tonk comedy", "Country / Folk", "Slow sad-funny honky-tonk country blues at 76 BPM with complete story verses, memorable chorus, bridge, and clean four-bar outro.", "Pedal steel, upright bass, brushed snare, saloon piano, clean electric guitar, and a small live bar-room band.", "a bearded-baritone-style adult country storyteller with warm grit, comic timing, clear lyrics, and believable live phrasing"),
    "folk_intimate": _p("Intimate folk", "Country / Folk", "Gentle acoustic folk at 78 BPM, warm and human, with narrative verses and a quiet resolving refrain.", "Fingerpicked steel-string guitar, soft upright bass, brushed snare, distant fiddle, and minimal room reverb.", "a close natural singer-songwriter voice with vulnerable detail, clean consonants, subtle breaths, and understated emotion"),
    "folk_bluegrass": _p("Bluegrass sprint", "Country / Folk", "Fast acoustic bluegrass at 164 BPM with driving verses, tight harmony chorus, and energetic instrumental breaks.", "Banjo rolls, mandolin chop, fiddle, flatpicked guitar, upright bass, and live ensemble harmonies.", "a bright agile roots singer with fast clear diction, authentic ensemble timing, and tight natural harmony responses"),
    "folk_americana": _p("Cinematic Americana", "Country / Folk", "Expansive Americana at 88 BPM with grounded storytelling, slow instrumental growth, and a weathered cinematic chorus.", "Acoustic guitar, tom-led drums, upright bass, tremolo electric guitar, pump organ, fiddle, and restrained group harmonies.", "a warm adult storyteller with distinct human texture, lucid lyrics, measured emotion, and a resonant unforced chorus"),
    "folk_celtic": _p("Celtic folk", "Country / Folk", "Lively Celtic folk at 118 BPM with dance pulse, modal melody, communal chorus, and a short instrumental reel.", "Fiddle, wooden flute, bodhrán, bouzouki, acoustic guitar, upright bass, and natural group voices.", "a clear spirited folk singer with storytelling warmth, precise words, nimble rhythm, and organic communal harmonies"),

    # Latin and global grooves
    "latin_pop": _p("Latin pop", "Latin / Global", "Polished Latin pop at 104 BPM with syncopated verses, a warm rising pre-chorus, and a bright romantic hook.", "Pop drums, nylon guitar, rounded bass, piano montuno touches, hand percussion, brass accents, and vocal harmonies.", "a charismatic adult pop singer with warm tone, agile rhythm, clear pronunciation, and an emotionally vivid chorus"),
    "latin_reggaeton": _p("Reggaeton", "Latin / Global", "Modern reggaeton at 96 BPM with locked dembow groove, sparse confident verses, and a highly memorable melodic hook.", "Dembow drums, deep sub bass, plucked synth motif, atmospheric pad, hand percussion, and selective vocal stacks.", "a confident adult vocalist blending rhythmic delivery and melody with crisp diction, relaxed swagger, and catchy hook phrasing"),
    "latin_salsa": _p("Salsa orchestra", "Latin / Global", "Energetic salsa at 176 BPM with clave-driven verses, call-and-response coro, and a rising mambo section.", "Piano montuno, tumbao bass, congas, bongos, timbales, brass section, cowbell, and responsive chorus vocals.", "a powerful agile salsa lead with brilliant rhythmic diction, natural call-and-response, and energetic improvised accents"),
    "global_afrobeat": _p("Afrobeats pop", "Latin / Global", "Buoyant Afrobeats at 106 BPM with layered syncopation, relaxed melodic verses, and a smooth infectious hook.", "Interlocking kick and percussion, warm bass, clean high guitar, marimba-like plucks, soft pads, shakers, and layered responses.", "a relaxed melodic adult vocalist with clear rhythmic phrasing, warm tone, understated charisma, and smooth harmony stacks"),
    "global_dancehall": _p("Dancehall", "Latin / Global", "Modern dancehall at 100 BPM with sparse bounce, rhythmic vocal pocket, and a strong compact refrain.", "Syncopated digital drums, round sub bass, bright keyboard stabs, percussive guitar, dub delays, and selective vocal responses.", "a charismatic adult vocalist with exact rhythmic diction, playful cadence, natural swagger, and a clearly sung hook"),
    "global_amapiano": _p("Amapiano", "Latin / Global", "Deep amapiano at 112 BPM with patient groove, spacious harmony, and gradually intensifying log-drum movement.", "Soft four-on-floor pulse, rolling log drum bass, jazzy keys, shakers, airy pad, hand percussion, and restrained vocal textures."),
    "global_citypop": _p("City pop", "Latin / Global", "Glossy eighties city pop at 112 BPM with sophisticated harmony, buoyant verses, and a luminous driving chorus.", "Slap bass, crisp drums, electric piano, chorus guitar, analog brass, saxophone accents, and polished backing vocals.", "a smooth bright adult singer with relaxed groove, crystal diction, tasteful vibrato, and elegant harmony layers"),
    "global_bollywood": _p("Bollywood dance", "Latin / Global", "Colorful cinematic dance-pop at 126 BPM with dramatic verse changes, rising percussion, and an exuberant ensemble hook.", "Dhol, tabla accents, punchy pop drums, string flourishes, plucked sitar-like lead, synth bass, brass, and group responses.", "an expressive agile adult lead with precise words, theatrical dynamics, ornamented melody, and joyful ensemble responses"),
    "global_dub": _p("Deep dub", "Latin / Global", "Heavy roots dub at 72 BPM with spacious one-drop groove, evolving mixer effects, and instrumental call-and-response.", "Deep bass, one-drop drums, skank guitar, organ bubble, melodica, spring reverb, tape echo, and live filter movements."),

    # Cinematic, anime, games and utility
    "cinematic_orchestra": _p("Cinematic orchestra", "Cinematic / Media", "A cinematic orchestral cue that begins sparsely, rises through one coherent thematic development, reaches a controlled peak, and resolves cleanly.", "Solo French horn, deep strings, low brass, restrained timpani, woodwind detail, and no choir."),
    "cinematic_tension": _p("Dark tension score", "Cinematic / Media", "Slow-burn thriller tension with patient escalation, irregular pulse, and one severe but controlled climax.", "Detuned sub bass, sparse tom impacts, distant metallic drone, prepared piano, dissonant strings, and granular pressure."),
    "cinematic_horror": _p("Psychological horror", "Cinematic / Media", "Intimate psychological-horror score with unstable silence, creeping texture, and an abrupt uncanny revelation rather than constant loudness.", "Bowed metal, breathy bass flute, detuned piano, subharmonic drone, string scratches, room tone, and one dry impact."),
    "cinematic_romance": _p("Romantic film cue", "Cinematic / Media", "Tender romantic film music with simple memorable theme, gradual harmonic warmth, and a restrained emotional crest.", "Felt piano, solo cello, soft string ensemble, acoustic guitar harmonics, and delicate woodwind color."),
    "anime_opening": _p("Anime opening", "Cinematic / Media", "High-energy anime opening song at 172 BPM with urgent verse, rapid pre-chorus ascent, explosive melodic hook, and a concise instrumental break.", "Driving live drums, bright distorted guitars, melodic bass, piano accents, sparkling synths, string lifts, and stacked chorus vocals.", "an energetic youthful adult singer with expressive Japanese-pop phrasing, excellent English diction, clear high notes, and emotionally vivid dynamics"),
    "anime_ballad": _p("Anime ending ballad", "Cinematic / Media", "Emotional anime ending ballad at 74 BPM with intimate opening, bittersweet harmonic rise, and a luminous final chorus.", "Piano, acoustic guitar, warm strings, soft drums, glockenspiel details, electric-guitar swell, and delicate harmonies.", "a tender clear adult singer with natural breath, precise English lyrics, restrained vibrato, and a deeply felt final lift"),
    "game_chiptune": _p("Arcade chiptune", "Cinematic / Media", "Fast melodic 8-bit chiptune at 156 BPM with a clear hook, level-like development, and tightly resolved loop structure.", "Square and triangle leads, noise-channel percussion, rapid arpeggios, pulse-wave bass, and compact countermelodies."),
    "game_boss": _p("Boss battle", "Cinematic / Media", "Intense hybrid boss-battle score at 148 BPM with recurring threat motif, escalating phases, and a decisive final hit.", "Aggressive strings, low brass, taiko-like drums, distorted guitar, synth bass, metallic impacts, and wordless texture without choir lyrics."),
    "game_cozy": _p("Cozy game village", "Cinematic / Media", "Gentle looping game music at 92 BPM with friendly melody, light variation, and a clean seamless-feeling resolution.", "Pizzicato strings, wooden flute, acoustic guitar, upright bass, hand percussion, glockenspiel, and soft accordion."),
    "media_documentary": _p("Hopeful documentary", "Cinematic / Media", "Modern documentary underscore with patient pulse, transparent harmony, and gradual forward-looking lift without melodrama.", "Felt piano, muted plucks, soft electronic pulse, cello, airy pad, mallets, and subtle acoustic percussion."),
    "media_trailer": _p("Epic trailer", "Cinematic / Media", "Three-stage cinematic trailer cue with restrained opening, accelerating middle, and one enormous rhythmically clear final statement.", "Low strings, brass, hybrid percussion, impacts, ticking pulse, risers, distorted synth bass, and a clean final cutoff."),
}
