"""Curated MiniMax H3 SFX / Foley directions for the API, studio, and Comfy node."""
from __future__ import annotations


def _p(
    name: str,
    category: str,
    description: str,
    *,
    kind: str = "oneshot",
    default_seconds: float = 3.0,
    space: str = "a neutral dry recording stage with no visible source",
) -> dict[str, object]:
    return {
        "name": name,
        "category": category,
        "description": description,
        "kind": kind,
        "default_seconds": default_seconds,
        "space": space,
    }


SFX_PRESETS: dict[str, dict[str, object]] = {
    # Impacts / hits
    "impact_soft_thud": _p(
        "Soft body thud",
        "Impacts",
        "A single soft low-frequency body thud with a short muted decay and no metallic ring.",
        kind="oneshot",
        default_seconds=2.0,
    ),
    "impact_wood_knock": _p(
        "Wood knock",
        "Impacts",
        "Two or three firm knocks on a solid wooden door or tabletop, dry and close-miked.",
        kind="oneshot",
        default_seconds=2.5,
        space="a small dry interior hallway",
    ),
    "impact_metal_clang": _p(
        "Metal clang",
        "Impacts",
        "A single bright metal clang with a short natural ring that dies cleanly, no music bed.",
        kind="oneshot",
        default_seconds=3.0,
    ),
    "impact_glass_break": _p(
        "Glass shatter",
        "Impacts",
        "A short glass shatter burst with tinkling fragments that settle quickly into silence.",
        kind="oneshot",
        default_seconds=3.5,
    ),
    "impact_punch": _p(
        "Foley punch",
        "Impacts",
        "A cinematic but believable body punch hit with a tight low thump and brief cloth rustle, no vocal reaction.",
        kind="oneshot",
        default_seconds=2.0,
    ),
    "impact_whoomp": _p(
        "Deep whoomp",
        "Impacts",
        "A deep subby whoomp impact with a fast attack and short controlled tail, suitable as a trailer hit.",
        kind="oneshot",
        default_seconds=3.0,
    ),
    # Whooshes / transitions
    "whoosh_soft_air": _p(
        "Soft air whoosh",
        "Whooshes",
        "A soft airy whoosh pan with gentle high-frequency texture and a clean fade, no tonal music.",
        kind="oneshot",
        default_seconds=2.0,
    ),
    "whoosh_fast_pass": _p(
        "Fast pass-by whoosh",
        "Whooshes",
        "A fast stereo pass-by whoosh with a sharp center peak and quick decay.",
        kind="oneshot",
        default_seconds=1.5,
    ),
    "whoosh_fabric_swipe": _p(
        "Fabric swipe",
        "Whooshes",
        "A short cloth or fabric swipe whoosh with dry close-mic detail.",
        kind="oneshot",
        default_seconds=1.5,
    ),
    "whoosh_sci_fi_sweep": _p(
        "Sci-fi sweep",
        "Whooshes",
        "A synthetic sci-fi energy sweep whoosh with a rising then falling texture, no melody and no speech.",
        kind="oneshot",
        default_seconds=3.0,
    ),
    "riser_short_tension": _p(
        "Short tension riser",
        "Whooshes",
        "A short non-musical tension riser built from filtered noise and air, cresting once then stopping. No drums, no score.",
        kind="oneshot",
        default_seconds=4.0,
    ),
    "stinger_dark_hit": _p(
        "Dark stinger hit",
        "Whooshes",
        "A single dark cinematic stinger: brief noise swell into a low hit, then silence. Not a musical chord stinger.",
        kind="oneshot",
        default_seconds=3.5,
    ),
    # UI / interface
    "ui_soft_click": _p(
        "Soft UI click",
        "UI",
        "A single soft tactile UI click, short and clean, like a premium button press.",
        kind="oneshot",
        default_seconds=1.5,
    ),
    "ui_toggle": _p(
        "UI toggle",
        "UI",
        "A short mechanical toggle or switch click with a tiny secondary tick.",
        kind="oneshot",
        default_seconds=1.5,
    ),
    "ui_notification_blip": _p(
        "Notification blip",
        "UI",
        "A short friendly non-melodic notification blip made of two soft electronic ticks, not a jingle.",
        kind="oneshot",
        default_seconds=2.0,
    ),
    "ui_error_buzz": _p(
        "Error buzz",
        "UI",
        "A brief low error buzz or rejected-action tone, non-musical and under one second of activity.",
        kind="oneshot",
        default_seconds=2.0,
    ),
    "ui_whoosh_panel": _p(
        "Panel open whoosh",
        "UI",
        "A tiny UI panel-open whoosh with a soft digital shimmer and immediate settle.",
        kind="oneshot",
        default_seconds=2.0,
    ),
    # Foley / objects
    "foley_footsteps_wood": _p(
        "Footsteps on wood",
        "Foley",
        "Several natural adult footsteps on a wooden floor, moderate pace, no voices, no score.",
        kind="oneshot",
        default_seconds=5.0,
        space="a quiet wooden interior room",
    ),
    "foley_footsteps_gravel": _p(
        "Footsteps on gravel",
        "Foley",
        "A short walk of gravel crunch footsteps outdoors, dry and clear.",
        kind="oneshot",
        default_seconds=5.0,
        space="an outdoor gravel path",
    ),
    "foley_door_open_close": _p(
        "Door open and close",
        "Foley",
        "A wooden interior door opens with handle click and hinge, brief pause, then closes with a solid latch.",
        kind="oneshot",
        default_seconds=5.0,
        space="a quiet residential interior",
    ),
    "foley_keys_jingle": _p(
        "Keys jingle",
        "Foley",
        "A short metallic keyring jingle and set-down on a hard surface.",
        kind="oneshot",
        default_seconds=3.0,
    ),
    "foley_paper_rustle": _p(
        "Paper rustle",
        "Foley",
        "Close paper page turns and light rustle, dry studio foley detail.",
        kind="oneshot",
        default_seconds=4.0,
    ),
    "foley_zipper": _p(
        "Zipper",
        "Foley",
        "A single jacket or bag zipper pull with realistic teeth texture.",
        kind="oneshot",
        default_seconds=2.5,
    ),
    "foley_cloth_movement": _p(
        "Cloth movement",
        "Foley",
        "Soft clothing rustle from a person shifting once, no footsteps layered over it unless implied lightly.",
        kind="oneshot",
        default_seconds=3.0,
    ),
    "foley_cup_set_down": _p(
        "Cup set down",
        "Foley",
        "A ceramic mug set onto a wooden table with a short ceramic clink.",
        kind="oneshot",
        default_seconds=2.0,
    ),
    # Nature / ambience beds
    "ambience_rain_window": _p(
        "Rain on window",
        "Ambience",
        "Steady gentle rain against a window with soft room tone, loopable and free of music or speech.",
        kind="loop_bed",
        default_seconds=12.0,
        space="indoors beside a rainy window",
    ),
    "ambience_forest_day": _p(
        "Daytime forest bed",
        "Ambience",
        "A calm daytime forest ambience with light wind in leaves and distant birds, no people talking.",
        kind="loop_bed",
        default_seconds=15.0,
        space="a quiet temperate forest",
    ),
    "ambience_city_night": _p(
        "City night bed",
        "Ambience",
        "Distant night city bed: low traffic wash, occasional far horn, soft HVAC-like tone, no intelligible voices.",
        kind="loop_bed",
        default_seconds=15.0,
        space="an urban apartment window at night",
    ),
    "ambience_room_tone": _p(
        "Quiet room tone",
        "Ambience",
        "Very quiet natural room tone with faint air and almost no events, suitable as a bed.",
        kind="loop_bed",
        default_seconds=10.0,
        space="a still untreated room",
    ),
    "ambience_ocean_shore": _p(
        "Ocean shore",
        "Ambience",
        "Gentle ocean waves on a shoreline with soft foam wash, continuous and non-musical.",
        kind="loop_bed",
        default_seconds=15.0,
        space="an open shoreline",
    ),
    "ambience_wind_gusts": _p(
        "Wind gusts",
        "Ambience",
        "Outdoor wind with a few stronger gusts through dry grass or light trees, no voices.",
        kind="loop_bed",
        default_seconds=12.0,
    ),
    "ambience_fireplace": _p(
        "Fireplace crackle",
        "Ambience",
        "Close fireplace crackle and low burn with occasional ember pops, cozy and continuous.",
        kind="loop_bed",
        default_seconds=12.0,
        space="beside a residential fireplace",
    ),
    "ambience_cafe_murmur": _p(
        "Cafe murmur bed",
        "Ambience",
        "Soft unintelligible cafe walla and dish clinks as background ambience only—no clear words, no music playlist.",
        kind="loop_bed",
        default_seconds=15.0,
        space="a busy cafe mid-distance",
    ),
    # Vehicles / machines
    "vehicle_car_pass": _p(
        "Car pass-by",
        "Vehicles",
        "A single car pass-by outdoors with Doppler motion and tire noise, no horn melody, no radio music.",
        kind="oneshot",
        default_seconds=5.0,
        space="an outdoor roadside",
    ),
    "vehicle_engine_start": _p(
        "Car engine start",
        "Vehicles",
        "A car ignition crank, engine catches, brief idle, then stop—or settle into idle if duration allows.",
        kind="oneshot",
        default_seconds=5.0,
    ),
    "machine_elevator_ding": _p(
        "Elevator ding",
        "Vehicles",
        "A single elevator arrival ding with optional soft door-open motor hum, no announcement voice.",
        kind="oneshot",
        default_seconds=3.0,
        space="inside a modern elevator lobby",
    ),
    "machine_printer": _p(
        "Office printer",
        "Vehicles",
        "A short office printer cycle: motor whir, paper feed, finish beep optional but non-melodic.",
        kind="oneshot",
        default_seconds=6.0,
    ),
    # Sci-fi / fantasy FX
    "scifi_teleport": _p(
        "Teleport materialize",
        "Sci-fi",
        "A sci-fi teleport materialize: rising energy texture, brief crackle, settle to silence. No dialogue, no theme music.",
        kind="oneshot",
        default_seconds=4.0,
    ),
    "scifi_shield_hit": _p(
        "Energy shield hit",
        "Sci-fi",
        "A single energy-shield impact with crystalline crack and short decay.",
        kind="oneshot",
        default_seconds=3.0,
    ),
    "scifi_ui_scan": _p(
        "Scanner sweep",
        "Sci-fi",
        "A short futuristic scanner sweep of soft electronic ticks and a filtered sweep, not a musical arpeggio.",
        kind="oneshot",
        default_seconds=3.5,
    ),
    "magic_sparkle_cast": _p(
        "Magic sparkle cast",
        "Sci-fi",
        "A fantasy spell-cast sparkle burst with shimmering high texture and quick fade, no choir or score.",
        kind="oneshot",
        default_seconds=3.5,
    ),
    "horror_dread_bed": _p(
        "Horror dread bed",
        "Sci-fi",
        "A low unease ambience bed of distant rumbles and sparse creaks, non-musical, no screams, no score stabs.",
        kind="loop_bed",
        default_seconds=12.0,
        space="an empty dark corridor",
    ),
    # Nature one-shots
    "nature_thunder_distant": _p(
        "Distant thunder",
        "Nature",
        "A single distant thunder roll with long soft decay and no rain unless lightly implied.",
        kind="oneshot",
        default_seconds=6.0,
        space="outdoors under a storm sky",
    ),
    "nature_bird_wing_flap": _p(
        "Bird wing flap",
        "Nature",
        "A close bird takeoff with a few wing flaps, no chirped melody line treated as music.",
        kind="oneshot",
        default_seconds=2.5,
    ),
    "nature_fire_ignite": _p(
        "Fire ignite",
        "Nature",
        "A match or lighter ignite and brief flame catch with crackle onset.",
        kind="oneshot",
        default_seconds=3.0,
    ),
    "nature_water_splash": _p(
        "Water splash",
        "Nature",
        "A single medium water splash with droplet settle, outdoor or bathroom-agnostic.",
        kind="oneshot",
        default_seconds=3.0,
    ),
    # Cinematic utility
    "cine_silence_tail": _p(
        "Silence with air",
        "Cinematic",
        "Near-silence carrying only the faintest room air, useful as a tail or spacer. No events, no music.",
        kind="loop_bed",
        default_seconds=5.0,
    ),
    "cine_heartbeat_pulse": _p(
        "Heartbeat pulse",
        "Cinematic",
        "A close human heartbeat pulse pattern, organic and non-musical, fading or holding as duration allows.",
        kind="oneshot",
        default_seconds=6.0,
    ),
    "cine_camera_shutter": _p(
        "Camera shutter",
        "Cinematic",
        "A single mechanical camera shutter click with short mirror slap character.",
        kind="oneshot",
        default_seconds=1.5,
    ),
    "cine_tape_start": _p(
        "Tape transport start",
        "Cinematic",
        "Analog tape or film transport start: button, motor spin-up, brief steady roll.",
        kind="oneshot",
        default_seconds=3.0,
    ),
}
