"""Aseprite bridge: save PNG sequences / sheets, and drive aseprite.exe headless
to assemble real .aseprite files (frames, durations, tags) and export sheets."""

import json
import os
import subprocess
import tempfile

import numpy as np
import torch
from PIL import Image

import folder_paths

from .pf_palettes import hex_to_rgb

CONFIG_FILE = os.path.join(os.path.dirname(__file__), "aseprite_path.txt")


def find_aseprite(explicit=""):
    candidates = []
    if explicit.strip():
        candidates.append(explicit.strip().strip('"'))
    if os.environ.get("ASEPRITE_EXE"):
        candidates.append(os.environ["ASEPRITE_EXE"])
    if os.path.isfile(CONFIG_FILE):
        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#"):
                    candidates.append(line)
    candidates += [
        r"C:\Program Files\Aseprite\Aseprite.exe",
        r"C:\Program Files (x86)\Aseprite\Aseprite.exe",
        r"C:\Program Files (x86)\Steam\steamapps\common\Aseprite\Aseprite.exe",
        r"D:\SteamLibrary\steamapps\common\Aseprite\Aseprite.exe",
    ]
    for c in candidates:
        if c and os.path.isfile(c):
            return c
    return None


def _to_rgba_pil(rgb_uint8, alpha_float):
    a = (np.clip(alpha_float, 0, 1) * 255).round().astype(np.uint8)
    rgba = np.dstack([rgb_uint8, a])
    return Image.fromarray(rgba, "RGBA")


def _save_counter(output_dir, prefix, ext):
    """prefix may contain subfolders; returns '<sub>/<base>_<NNNNN>_' (os separators)."""
    prefix = prefix.replace("/", os.sep)
    sub = os.path.dirname(prefix)
    base_name = os.path.basename(prefix)
    target_dir = os.path.join(output_dir, sub) if sub else output_dir
    os.makedirs(target_dir, exist_ok=True)
    counter = 1
    while True:
        name = "%s_%05d_" % (base_name, counter)
        if not any(f.startswith(name) and f.endswith(ext) for f in os.listdir(target_dir)):
            return os.path.join(sub, name) if sub else name
        counter += 1


def _build_lua(files, durations_ms, tag, out_ase, width, height):
    lines = [
        "-- generated by ComfyUI-PixelForge-H3",
        "local files = {%s}" % ",".join(json.dumps(p.replace("\\", "/")) for p in files),
        "local durs = {%s}" % ",".join(str(max(1, int(d))) for d in durations_ms),
        'local spr = Sprite(%d, %d, ColorMode.RGBA)' % (width, height),
        "for i = 2, #files do spr:newEmptyFrame() end",
        "for i, p in ipairs(files) do",
        "  local img = Image{ fromFile = p }",
        "  spr:newCel(spr.layers[1], i, img, Point(0,0))",
        "  spr.frames[i].duration = durs[i] / 1000.0",
        "end",
    ]
    if tag:
        lines += [
            "local t = spr:newTag(1, #files)",
            't.name = %s' % json.dumps(tag),
        ]
    lines += [
        'spr:saveAs(%s)' % json.dumps(out_ase.replace("\\", "/")),
        "spr:close()",
    ]
    return "\n".join(lines)


class PixelForgeAsepriteExport:
    """Save a cleaned sprite run to disk and (optionally) hand it to Aseprite's
    CLI to produce a .aseprite file + sheet + json, non-destructively."""

    CATEGORY = "PixelForge/export"
    FUNCTION = "run"
    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("report",)
    OUTPUT_NODE = True
    DESCRIPTION = "Write PNG sequence (+sheet+json), then optionally invoke aseprite.exe headless to build a tagged .aseprite file. No Aseprite install = PNGs+json only."

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "images": ("IMAGE",),
                "filename_prefix": ("STRING", {"default": "pixelforge/sprite"}),
                "tag_name": ("STRING", {"default": "run"}),
                "fps": ("FLOAT", {"default": 12.0, "min": 1.0, "max": 60.0}),
                "build_aseprite": ("BOOLEAN", {"default": True}),
                "aseprite_path": ("STRING", {"default": "",
                                             "tooltip": "Optional explicit path to Aseprite.exe. Auto-detects common installs, ASEPRITE_EXE env, or aseprite_path.txt next to this node pack."}),
            },
            "optional": {
                "alpha": ("MASK",),
                "durations_json": ("STRING", {"forceInput": True,
                                              "tooltip": "Wire PixelForgeFrameDedup here so merged frames get real durations."}),
            },
        }

    def run(self, images, filename_prefix, tag_name, fps, build_aseprite,
            aseprite_path, alpha=None, durations_json=None):
        rgb = (images.clamp(0, 1) * 255).round().to(torch.uint8).cpu().numpy()
        n, h, w, _ = rgb.shape
        am = None
        if alpha is not None:
            m = alpha.cpu().numpy()
            am = [m[min(i, m.shape[0] - 1)] for i in range(n)]

        durations_frames = None
        if durations_json:
            try:
                durations_frames = json.loads(durations_json).get("durations_frames")
            except Exception:
                durations_frames = None
        if not durations_frames or len(durations_frames) != n:
            durations_frames = [1] * n
        durations_ms = [max(1, int(round(1000.0 * d / fps))) for d in durations_frames]

        output_dir = folder_paths.get_output_directory()
        os.makedirs(output_dir, exist_ok=True)
        base = _save_counter(output_dir, filename_prefix.replace("/", os.sep), ".png")
        folder = os.path.join(output_dir, base + "frames")
        os.makedirs(folder, exist_ok=True)

        files = []
        ui_images = []
        for i in range(n):
            a = am[i] if am is not None else np.ones((h, w), dtype=np.float32)
            img = _to_rgba_pil(rgb[i], a)
            path = os.path.join(folder, "frame_%03d.png" % i)
            img.save(path)
            files.append(path)
            ui_images.append({"filename": "frame_%03d.png" % i,
                              "subfolder": os.path.relpath(folder, output_dir).replace(os.sep, "/"),
                              "type": "output"})

        manifest = {
            "tag": tag_name, "fps": fps, "frame_size": [w, h],
            "frames": [{"file": os.path.basename(p), "duration_ms": d}
                       for p, d in zip(files, durations_ms)],
        }
        manifest_path = os.path.join(folder, "frames.json")
        with open(manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=1)

        report = ["saved %d RGBA frames -> %s" % (n, folder),
                  "manifest -> %s" % manifest_path]

        exe = find_aseprite(aseprite_path) if build_aseprite else None
        if build_aseprite and exe is None:
            report.append("aseprite.exe not found - skipped .aseprite build "
                          "(set the path on the node, ASEPRITE_EXE, or aseprite_path.txt)")
        elif exe:
            out_ase = os.path.join(output_dir, base + tag_name + ".aseprite")
            lua = _build_lua(files, durations_ms, tag_name, out_ase, w, h)
            lua_path = os.path.join(folder, "_build_sprite.lua")
            with open(lua_path, "w", encoding="utf-8") as f:
                f.write(lua)
            try:
                proc = subprocess.run(
                    [exe, "-b", "--script", lua_path],
                    capture_output=True, text=True, timeout=300)
                if proc.returncode == 0 and os.path.isfile(out_ase):
                    report.append(".aseprite -> %s" % out_ase)
                    # second pass: export sheet + json from the built file
                    sheet_png = os.path.join(output_dir, base + "sheet.png")
                    sheet_json = os.path.join(output_dir, base + "sheet.json")
                    proc2 = subprocess.run(
                        [exe, "-b", out_ase, "--sheet", sheet_png,
                         "--data", sheet_json, "--format", "json-hash",
                         "--list-tags", "--sheet-pack"],
                        capture_output=True, text=True, timeout=300)
                    if proc2.returncode == 0 and os.path.isfile(sheet_png):
                        report.append("sheet -> %s" % sheet_png)
                        report.append("sheet json -> %s" % sheet_json)
                    else:
                        report.append("sheet export failed: %s" % (proc2.stderr or proc2.stdout))
                else:
                    report.append("aseprite build failed: %s" % (proc.stderr or proc.stdout))
            except subprocess.TimeoutExpired:
                report.append("aseprite timed out after 300s")

        return {"ui": {"images": ui_images},
                "result": ("\n".join(report),)}


class PixelForgeSaveGIF:
    """Save frames as an animated GIF (palette + transparency) into the output dir."""

    CATEGORY = "PixelForge/export"
    FUNCTION = "run"
    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("report",)
    OUTPUT_NODE = True
    DESCRIPTION = "Animated GIF export with nearest upscale, alpha -> GIF transparency, and loop control. Instant in-app preview + report of the saved path."

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "images": ("IMAGE",),
                "filename_prefix": ("STRING", {"default": "pixelforge/gif"}),
                "fps": ("FLOAT", {"default": 12.0, "min": 1.0, "max": 50.0}),
                "loop": ("BOOLEAN", {"default": True}),
                "upscale": ("INT", {"default": 1, "min": 1, "max": 16,
                                    "tooltip": "Nearest-neighbor upscale for the GIF only."}),
                # --- v3 widget appended (positional compat) ---
                "preview_webp": ("BOOLEAN", {"default": True,
                                             "tooltip": "Also write an animated .webp copy and use IT for the in-app "
                                                        "preview. The ComfyUI frontend treats animated .gif output as "
                                                        "video (which can't play GIF), so the GIF itself never previews. "
                                                        "The .gif is always saved either way."}),
            },
            "optional": {"alpha": ("MASK",),
                         "durations_json": ("STRING", {"forceInput": True})},
        }

    def run(self, images, filename_prefix, fps, loop, upscale, preview_webp=True,
            alpha=None, durations_json=None):
        rgb = (images.clamp(0, 1) * 255).round().to(torch.uint8).cpu().numpy()
        n, h, w, _ = rgb.shape
        am = None
        if alpha is not None:
            m = alpha.cpu().numpy()
            am = [m[min(i, m.shape[0] - 1)] for i in range(n)]

        durations = None
        if durations_json:
            try:
                df = json.loads(durations_json).get("durations_frames")
                if df and len(df) == n:
                    durations = [max(20, int(round(1000.0 * d / fps))) for d in df]
            except Exception:
                durations = None
        if durations is None:
            durations = [max(20, int(round(1000.0 / fps)))] * n

        # Build ONE shared GIF palette across the whole animation: exact when
        # frames are already palette-locked (<=255 unique opaque colors), else a
        # single median-cut on the stacked strip. Per-frame re-quantize caused
        # color flicker and mud. Index 255 is reserved for transparency.
        opaque = []
        for i in range(n):
            a = am[i] if am is not None else np.ones((h, w), dtype=np.float32)
            px = rgb[i][a > 0.5]
            if px.size:
                opaque.append(px)
        if opaque:
            uniq = np.unique(np.concatenate(opaque, 0).reshape(-1, 3), axis=0)
        else:
            uniq = rgb[0].reshape(-1, 3)
        if len(uniq) <= 255:
            gif_pal = uniq.astype(np.uint8)
        else:
            strip = Image.fromarray(np.concatenate([rgb[i] for i in range(n)], 0))
            q = strip.quantize(colors=255, method=Image.Quantize.MEDIANCUT,
                               dither=Image.Dither.NONE)
            raw = q.getpalette()[:255 * 3]
            gif_pal = np.array(raw, dtype=np.uint8).reshape(-1, 3)

        frames = []
        any_transparent = False
        from .pf_pixelize import _nearest_palette_map
        for i in range(n):
            a = am[i] if am is not None else np.ones((h, w), dtype=np.float32)
            if upscale > 1:
                img = _to_rgba_pil(rgb[i], a).resize((w * upscale, h * upscale),
                                                     Image.Resampling.NEAREST)
                frgb = np.asarray(img)[:, :, :3]
                amask = np.asarray(img)[:, :, 3] >= 128
            else:
                frgb = rgb[i]
                amask = a > 0.5
            any_transparent = any_transparent or bool((~amask).any())
            idx = _nearest_palette_map(frgb.astype(np.float32),
                                       gif_pal.astype(np.float32), "rgb")
            idx = np.where(amask, idx, 255).astype(np.uint8)
            q = Image.fromarray(idx, "P")
            pal = gif_pal.reshape(-1).tolist() + [0] * (768 - gif_pal.size)
            q.putpalette(pal)
            if any_transparent:
                q.info["transparency"] = 255
            frames.append(q)

        output_dir = folder_paths.get_output_directory()
        base = _save_counter(output_dir, filename_prefix.replace("/", os.sep), ".gif")
        path = os.path.join(output_dir, base + ".gif")
        save_kw = dict(save_all=True, append_images=frames[1:],
                       duration=durations, loop=0 if loop else 1,
                       optimize=False)
        if any_transparent:
            save_kw.update(disposal=2, transparency=255)
        frames[0].save(path, **save_kw)

        # In-app preview: the current ComfyUI frontend classifies any animated
        # output that is not .webp/.png as VIDEO (isVideoOutput), so a .gif ui
        # entry is fed to a <video> element and never renders. Save an animated
        # lossless .webp twin and preview THAT (same contract as core
        # SaveAnimatedWEBP); the .gif on disk is untouched.
        preview_path = path
        if preview_webp:
            preview_path = os.path.join(output_dir, base + ".webp")
            webp_frames = []
            for i in range(n):
                a = am[i] if am is not None else np.ones((h, w), dtype=np.float32)
                img = _to_rgba_pil(rgb[i], a)
                if upscale > 1:
                    img = img.resize((w * upscale, h * upscale),
                                     Image.Resampling.NEAREST)
                webp_frames.append(img)
            webp_frames[0].save(preview_path, save_all=True,
                                append_images=webp_frames[1:],
                                duration=durations, loop=0 if loop else 1,
                                lossless=True, quality=100, method=4)

        rel = os.path.relpath(preview_path, output_dir).replace(os.sep, "/")
        sub = os.path.dirname(rel)
        report = "saved gif -> %s (%d frames, %.1f fps%s)" % (
            path, n, fps, ", transparent" if any_transparent else "")
        if preview_webp:
            report += "\npreview webp -> %s" % preview_path
        return {"ui": {"images": [{"filename": os.path.basename(preview_path),
                                   "subfolder": "" if sub in ("", ".") else sub,
                                   "type": "output"}],
                       "animated": (True,)},
                "result": (report,)}


NODE_CLASS_MAPPINGS = {
    "PixelForgeAsepriteExport": PixelForgeAsepriteExport,
    "PixelForgeSaveGIF": PixelForgeSaveGIF,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    "PixelForgeAsepriteExport": "Aseprite Export (PixelForge)",
    "PixelForgeSaveGIF": "Save Sprite GIF (PixelForge)",
}
